version: 2
jobs:
  test:
    docker:
      - image: circleci/node:lts
    environment:
      - NODE_ENV: development
    working_directory: ~/TSCodeChallenges
    steps:
      - checkout
      - restore_cache:
          key: ts-code-challenges-yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn Install
          command: |
            yarn install
      - save_cache:
          key: ts-code-challenges-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/TSCodeChallenges/node_modules
      - run:
          name: Run JS Tests
          command: yarn test --maxWorkers=2
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
